### ISSUE TITLE
Error while setting up platform for sensor. 

### ISSUE THREAD

**Issue by shiitbiird** [andyalm/homeassistant-scout-alarm#12]
Logger: homeassistant.components.sensor
Source: custom_components/scout_alarm/api/scout_session.py:52
Integration: Sensor (documentation, issues)
First occurred: 7:10:04 PM (1 occurrences)
Last logged: 7:10:04 PM

Error while setting up scout_alarm platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/scout_alarm/sensor.py", line 36, in async_setup_entry
    devices = await location_api.get_devices()
  File "/config/custom_components/scout_alarm/api/scout_api.py", line 66, in get_devices
    location = await self.get_current_location()
  File "/config/custom_components/scout_alarm/api/scout_api.py", line 76, in get_current_location
    current_member = await self.__async_current_member()
  File "/config/custom_components/scout_alarm/api/scout_api.py", line 89, in __async_current_member
    self.__current_member = await self.__api.get_current_member()
  File "/config/custom_components/scout_alarm/api/scout_api.py", line 13, in get_current_member
    return await self.__http('GET', '/auth')
  File "/config/custom_components/scout_alarm/api/scout_api.py", line 37, in __http
    jwt = await self.session.async_get_token()
  File "/config/custom_components/scout_alarm/api/scout_session.py", line 18, in async_get_token
    self._jwt = await self.__get_fresh_jwt()
  File "/config/custom_components/scout_alarm/api/scout_session.py", line 52, in __get_fresh_jwt
    return (await response.json())['jwt']
KeyError: 'jwt'

**Comment by shiitbiird** [comment]
Scratch that... fixed it.

**Comment by jakecolman** [comment]
What was the issue?

**Comment by shiitbiird** [comment]
100% user error haha. I configured my YAML file rather than setting up through the UI and it threw a bunch of errors. Once I got rid of the YAML entry, I was able to configure through the UI. Everything has been working perfectly now (and super fast). Thank you guys for all your hard work here! Well done!
