### ISSUE TITLE
"TypeError: string indices must be integers" when running an automation

### ISSUE THREAD

**Issue by ghost** [andyalm/homeassistant-scout-alarm#22]
I have two automations set up with the exposed sensors. One to arm it at a certain time, one to disarm it at a certain time. Both worked great for a long time, but now they both cease to work.

Here's the traceback from home assistant whenever I debug the automations:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 688, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 76, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/device_action.py", line 116, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/scout_alarm/alarm_control_panel.py", line 159, in async_alarm_arm_night
    night_mode = self.__mode_for_state(STATE_ALARM_ARMED_NIGHT)
  File "/config/custom_components/scout_alarm/alarm_control_panel.py", line 251, in __mode_for_state
    matching_modes = [m for m in self._modes if m['name'] == mode_name]
  File "/config/custom_components/scout_alarm/alarm_control_panel.py", line 251, in <listcomp>
    matching_modes = [m for m in self._modes if m['name'] == mode_name]
TypeError: string indices must be integers

**Comment by andyalm** [comment]
I'm sorry to hear that. Reading the stack trace, I'm not really sure why that would be happening. My best guess is that something is going wrong when the component is initializing that is preventing `self._modes` from being initialized properly. If you have not already, could you try removing and re-adding the integration from your home assistant instance? If that doesn't work, it might help to see the home assistant logs when the scout integration is initializing.

**Comment by ghost** [comment]
Yep, taking it out and readding it fixed it! Thanks!
